# Generated by Django 3.2.6 on 2021-08-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('expired', 'Expired'), ('valid', 'Valid'), ('fraud', 'Fraud')], default='pending', max_length=8),
        ),
    ]
