# Generated by Django 3.2.6 on 2021-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_validationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('expired', 'Expired'), ('valid', 'Valid'), ('fraud', 'Fraud'), ('error', 'Error')], default='pending', max_length=8),
        ),
    ]
